### ISSUE TITLE
armv7? Not really

### ISSUE THREAD

**Issue by MagaTailor** [warricksothr/RustBuild#11]
I've just noticed the `armhf` [target's](https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/arm_unknown_linux_gnueabihf.rs#L25) code generation was actually geared towards `v6` for compatibility.

Seeing as you already provide separate `armv6` builds it makes sense for the `armv7` ones to **generate** code for `v7`, incl. at the time of bootstrapping themselves (curiously it's the default on [android.](https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/arm_linux_androideabi.rs#L15))

Literally we're talking about just two commands before the start of the armv7 build:

`sed -i s/v6/v7/ src/librustc_back/target/arm_unknown_linux_gnueabihf.rs`

and

`sed -i s/v6/v7/ mk/cfg/arm-unknown-linux-gnueabihf.mk`

To try out the proposed changes anyone can use the scripts from my [fork](https://github.com/petevine/RustBuild_v7).

**Comment by petevine** [comment]
Literally we're talking about just two commands before the start of the build:

`sed -i s/v6/v7/ src/librustc_back/target/arm_unknown_linux_gnueabihf.rs`

and

`sed -i s/v6/v7/ mk/cfg/arm-unknown-linux-gnueabihf.mk`

**Comment by warricksothr** [comment]
Good catch! I'll make the changes and kick off a test build tonight and see if I can run a resulting binary on my odroid.

**Comment by MagaTailor** [comment]
No worries, I never suggested adding `+neon` to the default set of features :)

**Comment by MagaTailor** [comment]
Can we close it? There's probably going to be an official `armv7` target anyway so you'll simply switch to that once it's available.

**Comment by warricksothr** [comment]
Sure, Any news on when that's going to be added as a target?

**Comment by MagaTailor** [comment]
Not clear yet, but you could add your two cents in that open Rpi PR.

**Comment by MagaTailor** [comment]
It's done, the new target is called:

`armv7-unknown-linux-gnueabihf`

However switching to it will require a rebuild of the last stage0 snapshot first, after adding the new target to the list.

**Comment by petevine** [comment]
However switching to it will require a rebuild of the last `stage0` snapshot first after adding the new target to the list.

**Comment by warricksothr** [comment]
Good to know. I'll try to get a snapshot built.
