### ISSUE TITLE
Standard links for fetching rust lib

### ISSUE THREAD

**Issue by tekjar** [warricksothr/RustBuild#12]
Hi. Thanks for this repo.

I'm planning to write a script which checks current installed rust version and fetches correct rustlib from this repo, and extract it into `/usr/local/lib/rustlib`. (Now my rust will be ready for cross compilation)

But that seems difficult with current dropbox links. E.g --> `https://www.dropbox.com/s/qe2xzttvlywlmd2/rustlib-1.5.0-stable-2015-12-04-3d7cd77-arm-unknown-linux-gnueabihf-1be195a1f195c6515d05a2a287ade45f3ba3efda.tar.gz?dl=0`

Is it possible to make the links simpler so that hard coding the link is easy?

**Comment by warricksothr** [comment]
Afraid that dropbox links are just that way. You could use my linking service to get the latest for the stable branch. But that'll change every 6 weeks as rust moves forward.

https://sothr.com/RustBuild/armv7/rustlib/stable/latest

I've been considering adding version specific mappings to the linker, but haven't gotten around to it. You're welcome to make a pull request with the added functionality to the linker service code. https://github.com/warricksothr/RustBuild-Linker
