### ISSUE TITLE
Use latest LLVM without rebuilding every time

### ISSUE THREAD

**Issue by MagaTailor** [warricksothr/RustBuild#15]
It's been possible to use the system LLVM for quite a while but it's probably better to use the bundled, updated source. Here's what I've been doing lately:

Once llvm gets updated, do a full llvm build, preserve the llvm directory. On every subsequent Rust build it's possible to:
- run `configure`
- remove `target-triple/llvm`
- link to the previously saved llvm directory in `target-triple`
- enter the newly linked llvm dir and invoke:
  `find . -exec touch {} \;`
- continue normally with `make`.

I'm curious how well this method compares to ccache, as similar to using `--llvm-root`, you get to stage0 immediately.

**Comment by petevine** [comment]
@alexcrichton
Wouldn't it be preferable to use this method in Travis which at the moment builds against llvm 3.7?

**Comment by MagaTailor** [comment]
https://github.com/rust-lang/rust/pull/32839
