### ISSUE TITLE
Shortcut links are broken for cargo stable and beta

### ISSUE THREAD

**Issue by marcust** [warricksothr/RustBuild#18]
The shortcut links 
https://sothr.com/RustBuild/armv7/cargo/beta/latest

https://sothr.com/RustBuild/armv7/cargo/stable/latest

both give 404s.

**Comment by warricksothr** [comment]
It looks like Cargo isn't building on 1.8 and 1.7 for ARMv7. I think I made a change for nightly related to this and as a result am now getting cargo build errors.

Looking into it.
