### ISSUE TITLE
Add instructions how to properly install/uninstall Rust from prebuilt binaries

### ISSUE THREAD

**Issue by andresv** [warricksothr/RustBuild#3]
It would be really convenient.

**Comment by warricksothr** [comment]
Sure, I'll put some documentation together about installing/uninstalling and using the unofficial binaries.

Most likely I'll gear the documentation to using multirust to manage them since that's how I've typically managed my installed rust versions.

**Comment by warricksothr** [comment]
Added instructions to the README
